export const AUTOMATION_LIST = [
  {
    to: 'super-easy-sms',
    title: 'super-easy-sms',
    contentText: 'Message',
    description: '기간별 정산 및 템플릿 문자보내기',
    icon: 'card',
    status: 'active',
  },
  {
    to: 'simple-message',
    title: 'simple-message',
    contentText: 'Simple Message',
    description: '간단히 메세지 보내요',
    icon: 'card',
    status: 'active',
  },
  {
    to: 'excel-student-import',
    title: 'excel-student-import',
    contentText: 'EXCEL로 학생 불러오기',
    description: '학생 데이터를 아주쉽게 가져오세요!',
    icon: 'grid',
    status: 'active',
  },
  {
    to: 'excel-class-import',
    title: 'excel-class-import',
    contentText: 'EXCEL로 수업 불러오기',
    description: '수업 데이터를 아주쉽게 가져오세요!',
    icon: 'grid',
    status: 'active',
  },
  {
    to: 'student-attendance/home',
    title: 'student-attendance',
    contentText: '학생 출결',
    description: '요놈들이 땡땡이를 쳤나?',
    icon: 'people',
    status: 'deactive',
  },
  {
    to: 'students-time-table',
    title: 'Time Table',
    contentText: '시간표',
    description: '아름다운 시간표 자동생성기',
    icon: 'calendar',
    status: 'deactive',
  },
  {
    to: 'send-email',
    title: 'Email',
    contentText: 'Email',
    description: '이메일 보내기!',
    icon: 'email',
    status: 'deactive',
  },
  {
    to: 'send-kakao-talk',
    title: 'send-kakao-talk',
    contentText: 'Kakao Talk',
    description: '카카오톡 보내기',
    icon: 'chat',
    status: 'deactive',
  },
];
